<a href="https://colab.research.google.com/github/shipragupta-2000/same/blob/master/all_ml_algo_on_iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import sklearn as sk
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
dataset=pd.read_csv("/content/iris.csv")
clf=DecisionTreeClassifier()
print(dataset.shape)

(150, 5)


splitting data to x and y


In [0]:
x=dataset.iloc[:,0:4].values
y=dataset.iloc[:,4].values

preprocessing y to convert class to 0 and 1

In [0]:
from sklearn.preprocessing import LabelEncoder
y=LabelEncoder().fit_transform(y)

In [0]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4)

training model using variou algo

1.   Logistic Regression



In [0]:
from sklearn.linear_model import LogisticRegression 
logmodel=LogisticRegression()
logmodel.fit(x_train,y_train)
y_pred=logmodel.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

95.0


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  2, 22]])

2.   K-Nearest Neighbour



In [0]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=5,metric='minkowski',p=2)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
y_pred=knn.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

96.66666666666667


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 23]])

3.   Naive Bayes



In [0]:
from sklearn.naive_bayes import GaussianNB
naive= GaussianNB()
naive.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
y_pred=naive.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

96.66666666666667


array([[20,  0,  0],
       [ 0, 16,  0],
       [ 0,  2, 22]])

4.   SVM



In [0]:
from sklearn.svm import SVC
sig=SVC(kernel='sigmoid')
sig.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='sigmoid',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred=sig.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

26.666666666666668


array([[ 0, 20,  0],
       [ 0, 16,  0],
       [ 0, 24,  0]])

In [0]:
linear=SVC(kernel='linear')
linear.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred=linear.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

98.33333333333333


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  0, 24]])

In [0]:
rbf=SVC(kernel='rbf')
rbf.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred=rbf.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

95.0


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  2, 22]])

In [0]:
pol=SVC(kernel='poly')
pol.fit(x_train,y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='poly',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [0]:
y_pred=pol.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

96.66666666666667


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  1, 23]])



5.   Random Forest



In [0]:
from sklearn.ensemble import RandomForestClassifier
ran=RandomForestClassifier()
ran.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
y_pred=ran.predict(x_test)
count=0
for i in range(0,y_pred.shape[0]):
  if y_pred[i]==y_test[i]:
    count=count+1
accuracy=(count/y_pred.shape[0])*100
print(accuracy)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

93.33333333333333


array([[20,  0,  0],
       [ 0, 15,  1],
       [ 0,  3, 21]])